image: node:latest
cache:
  paths:
    - node_modules/
pages:
  stage: deploy
  script:
    - npm i
    - npx rollup --config rollup.config.js
    - mkdir .public
    - cp -r dist .public/
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - main

