export const AllMaps = [
  "dsds/frog_cave_cave_only.png",
  "dsds/space_one.png",
  "dsds/halloween.png",
  "dsds/spaceshipint.png",
  "dsds/frog.png",
  "dsds/thebigmap.png",
  "dsds/asymcave.png",
  "dsds/tentacules.png",
  "dsds/eyes.png",
  "dsds/thesmallermap.png",
  "dsds/frog_only_frog.png",
  "dsds/420.png",
  "qmaps/qmap8.png",
  "qmaps/qmap9.png",
  "qmaps/qmap20.png",
  "qmaps/qmap18.png",
  "qmaps/qmap19.png",
  "qmaps/qmap17.png",
  "qmaps/qmap16.png",
  "qmaps/qmap14.png",
  "qmaps/qmap15.png",
  "qmaps/qmap11.png",
  "qmaps/qmap10.png",
  "qmaps/qmap12.png",
  "qmaps/qmap13.png",
  "qmaps/qmap4.png",
  "qmaps/qmap5.png",
  "qmaps/qmap7.png",
  "qmaps/qmap6.png",
  "qmaps/qmap2.png",
  "qmaps/qmap3.png",
  "qmaps/qmap1.png",
  "kangaroo/jetmen1+bunnyhop.png",
  "kangaroo/asshat_temple.png",
  "kangaroo/jetmen1_extended.png",
  "kangaroo/MountDoom2.png",
  "kangaroo/giger3.png",
  "kangaroo/lunar_dig.png",
  "kangaroo/guernica2.png",
  "kangaroo/gonad2.png",
  "kangaroo/pod_arena__extended_.png",
  "kangaroo/pod_arena4.png",
  "kangaroo/dali_ffa.png",
  "kangaroo/got4.png",
  "pilaf/g3a.png",
  "pilaf/hole.png",
  "piebaron/PB_Vents_00.lev",
  "kangaroo/white wolf.lev",
  "kangaroo/yennefer.lev",
  "kangaroo/liero2a.lev",
  "pilaf/racetrack1.lev",
  "pilaf/axiom.lev",
  "pilaf/oath.lev",
  "pilaf/webliero.lev",
  "hellhole/lieropower.lev",
  "hellhole/dtunnel.lev",
  "hellhole/handz.lev",
  "hellhole/mine_1.lev",
  "hellhole/Loadoff.lev",
  "hellhole/jolt.lev",
  "hellhole/Puzzle.LEV",
  "hellhole/Thing.lev",
  "hellhole/2xcathode.lev",
  "hellhole/pokemon.lev",
  "hellhole/bunkers_2.lev",
  "hellhole/Guardian.lev",
  "hellhole/house_2.lev",
  "hellhole/Crash Zone.lev",
  "hellhole/STEE.LEV",
  "hellhole/nike.lev",
  "hellhole/phobos.lev",
  "hellhole/crazy_2.lev",
  "hellhole/#139#.LEV",
  "hellhole/delinha.lev",
  "hellhole/Mission4.lev",
  "hellhole/Martini.lev",
  "hellhole/Arena_2.lev",
  "hellhole/rudi.lev",
  "hellhole/666.lev",
  "hellhole/Castle2.lev",
  "hellhole/X-treme Forts.lev",
  "hellhole/Diablo.lev",
  "hellhole/MGM1.LEV",
  "hellhole/ROCKDUDE.LEV",
  "hellhole/Wolf Lava Arena.lev",
  "hellhole/confusing.lev",
  "hellhole/blank.lev",
  "hellhole/Kazakhstan warehouse.lev",
  "hellhole/tri fort.lev",
  "hellhole/destroy2.lev",
  "hellhole/spikcavn.lev",
  "hellhole/Mine.lev",
  "hellhole/B Class DD High.lev",
  "hellhole/The D11-Base.lev",
  "hellhole/LABRIN.LEV",
  "hellhole/Elevate.lev",
  "hellhole/manson.lev",
  "hellhole/Mission5.lev",
  "hellhole/Bridge.lev",
  "hellhole/bloodcity2.lev",
  "hellhole/City.lev",
  "hellhole/UA-METRO.LEV",
  "hellhole/tower_1.lev",
  "hellhole/serial.lev",
  "hellhole/oro2.lev",
  "hellhole/hell.lev",
  "hellhole/RockTest.lev",
  "hellhole/Chook Arena.lev",
  "hellhole/Gestapo.lev",
  "hellhole/Hus3.lev",
  "hellhole/Open level.lev",
  "hellhole/lego.lev",
  "hellhole/GOZONTAI.LEV",
  "hellhole/Dzuma.lev",
  "hellhole/N2O.lev",
  "hellhole/forrest.lev",
  "hellhole/Moonbase.lev",
  "hellhole/Mk3 Reefer.lev",
  "hellhole/izbla.lev",
  "hellhole/bird.lev",
  "hellhole/Roper.lev",
  "hellhole/TORTELIN.LEV",
  "hellhole/KillEm.lev",
  "hellhole/Owl-3.lev",
  "hellhole/Shitbreak.lev",
  "hellhole/missile2.lev",
  "hellhole/war Bubbles of doom.lev",
  "hellhole/slop.lev",
  "hellhole/deck18.lev",
  "hellhole/kulon-q8.lev",
  "hellhole/house_1.lev",
  "hellhole/UH OH OH.LEV",
  "hellhole/NR1.LEV",
  "hellhole/BUNKERS_1.LEV",
  "hellhole/ROCK1.LEV",
  "hellhole/crazy_1.lev",
  "hellhole/cow.lev",
  "hellhole/TOM.LEV",
  "hellhole/TOMTOM.LEV",
  "hellhole/Mission7.lev",
  "hellhole/canyon.lev",
  "hellhole/6xwheel.lev",
  "hellhole/quickdef.lev",
  "hellhole/Rockymon.lev",
  "hellhole/Disney.lev",
  "hellhole/walls.lev",
  "hellhole/Kross4.lev",
  "hellhole/Arena_1.lev",
  "hellhole/supermario.lev",
  "hellhole/BellCity.lev",
  "hellhole/Lost.lev",
  "hellhole/GreyUFO.lev",
  "hellhole/drains.lev",
  "hellhole/aqueducts.lev",
  "hellhole/MGM2.LEV",
  "hellhole/First Map.lev",
  "hellhole/MGM3.LEV",
  "hellhole/Jnglenight.lev",
  "hellhole/scuba.lev",
  "hellhole/ulvenstn.lev",
  "hellhole/ARENA4.LEV",
  "hellhole/STONED.LEV",
  "hellhole/B Class DD Low.lev",
  "hellhole/Commando.lev",
  "hellhole/flyluft.lev",
  "hellhole/4bases.lev",
  "hellhole/deadling.lev",
  "hellhole/Leaking.lev",
  "hellhole/Mission6.lev",
  "hellhole/MITH.lev",
  "hellhole/fro.lev",
  "hellhole/tiger.lev",
  "hellhole/TEMPLE27.LEV",
  "hellhole/TOWER_2.LEV",
  "hellhole/sections.lev",
  "hellhole/Church.lev",
  "hellhole/Paras2.lev",
  "hellhole/tunnel.lev",
  "hellhole/BOWSERPL.LEV",
  "hellhole/Slime.lev",
  "hellhole/sheep.lev",
  "hellhole/Owl-2.lev",
  "hellhole/gay.lev",
  "hellhole/angel.lev",
  "hellhole/Forest.lev",
  "hellhole/arina.lev",
  "hellhole/takta.lev",
  "hellhole/fujita.lev",
  "hellhole/AHHHHHH.LEV",
  "hellhole/Crater.lev",
  "hellhole/impossbl.lev",
  "hellhole/pipes.lev",
  "hellhole/warloops.lev",
  "hellhole/blowgoat.lev",
  "hellhole/Water2.lev",
  "hellhole/Snow.lev",
  "hellhole/Lightning volcano.lev",
  "hellhole/dahhhhhhhh.lev",
  "hellhole/Field.lev",
  "hellhole/Krig.lev",
  "hellhole/splat.lev",
  "hellhole/Metro.lev",
  "hellhole/volcano.lev",
  "hellhole/OneWay.lev",
  "hellhole/Twister.lev",
  "hellhole/rock.lev",
  "hellhole/little town.lev",
  "hellhole/caverna.lev",
  "hellhole/ny av meg.lev",
  "hellhole/JUSSI2.LEV",
  "hellhole/Mission2.lev",
  "hellhole/gaper.lev",
  "hellhole/GMT3beta32.lev",
  "hellhole/UA-STREETS.LEV",
  "hellhole/LAB!_1.lev",
  "hellhole/juka.lev",
  "hellhole/jumpbase.lev",
  "hellhole/Battle-field.lev",
  "hellhole/STONEAGE.LEV",
  "hellhole/Playgrou.lev",
  "hellhole/Turbo.lev",
  "hellhole/face.lev",
  "hellhole/FF8.lev",
  "hellhole/BALTIC.lev",
  "hellhole/OwnSides.lev",
  "hellhole/no mar.lev",
  "hellhole/1337.lev",
  "hellhole/guns.lev",
  "hellhole/gorilla.lev",
  "hellhole/winter.lev",
  "hellhole/warzone2.lev",
  "hellhole/TEMPLE_1.LEV",
  "hellhole/MGM6.LEV",
  "hellhole/trench.lev",
  "hellhole/EnterpriseClass.lev",
  "hellhole/SPcsupp.lev",
  "hellhole/Dino.lev",
  "hellhole/H2O.lev",
  "hellhole/cruiser.lev",
  "hellhole/multiplicity.lev",
  "hellhole/underground bunker 2.lev",
  "hellhole/RU.LEV",
  "hellhole/ROCKBASE.LEV",
  "hellhole/pool.lev",
  "hellhole/scene3.lev",
  "hellhole/EXPL-RAIL.LEV",
  "hellhole/Mission3.lev",
  "hellhole/Statues1.lev",
  "hellhole/CVICISTE.LEV",
  "hellhole/Cartman.lev",
  "hellhole/Chaos I.LEV",
  "hellhole/hvymetal.lev",
  "hellhole/slot.lev",
  "hellhole/Egypt_2.lev",
  "hellhole/NOTHING.LEV",
  "hellhole/Maze_1.lev",
  "hellhole/planetx.lev",
  "hellhole/Grissom.lev",
  "hellhole/Gato400.lev",
  "hellhole/spike.lev",
  "hellhole/LOSER.LEV",
  "hellhole/Riverraid.lev",
  "hellhole/karrrllls.lev",
  "hellhole/Dome.lev",
  "hellhole/LSTAtsea.lev",
  "hellhole/butterfly.lev",
  "hellhole/TheCave.lev",
  "hellhole/panther.lev",
  "hellhole/kickass.lev",
  "hellhole/Training_1.lev",
  "hellhole/qflight.lev",
  "hellhole/sign.lev",
  "hellhole/NCC-2000 Excelsior.lev",
  "hellhole/planetz.lev",
  "hellhole/Thewell.lev",
  "hellhole/City Of the Night.lev",
  "hellhole/IMLOST.LEV",
  "hellhole/BUNKRY.LEV",
  "hellhole/Mission1.lev",
  "hellhole/DUEL.LEV",
  "hellhole/Island War.lev",
  "hellhole/remorse.lev",
  "hellhole/flyndie.lev",
  "hellhole/dotty.lev",
  "hellhole/l_turbo.lev",
  "hellhole/circles.lev",
  "hellhole/Platforms.lev",
  "hellhole/BOOM_1.lev",
  "hellhole/wcav.lev",
  "hellhole/Carvings.LEV",
  "hellhole/finlfigt.lev",
  "hellhole/blood.lev",
  "hellhole/illusion.lev",
  "hellhole/spring.lev",
  "hellhole/MGM4.LEV",
  "hellhole/rompe.lev",
  "hellhole/MGM5.LEV",
  "hellhole/PATTERN.LEV",
  "hellhole/CTFArena_1.lev",
  "hellhole/LENNUK.LEV",
  "hellhole/LEVaYTYS.LEV",
  "hellhole/Elegant.lev",
  "hellhole/LAIR.LEV",
  "hellhole/Kross3.lev",
  "hellhole/MArio Factory.lev",
  "hellhole/Owl.lev",
  "hellhole/Saladin.lev",
  "hellhole/Worlddom.lev",
  "hellhole/Carnival.lev",
  "hellhole/hardwrld.lev",
  "hellhole/Battleground.lev",
  "hellhole/Labra.lev",
  "hellhole/Reliant.lev",
  "hellhole/nav_dm.lev",
  "hellhole/Cathode_1.lev",
  "hellhole/shayss.lev",
  "hellhole/lb_cmplx.lev",
  "hellhole/Ramm.lev",
  "hellhole/Statues2.lev",
  "hellhole/lift.lev",
  "hellhole/rally.lev",
  "hellhole/bunnycat.lev",
  "hellhole/Maze_2.lev",
  "hellhole/Egypt_1.lev",
  "hellhole/Pyromide.lev",
  "hellhole/big.lev",
  "hellhole/rockar3.lev",
  "hellhole/Regula.lev",
  "hellhole/Molehole.lev",
  "hellhole/House.lev",
  "hellhole/Forest2.lev",
  "hellhole/AfricanBonanza2.lev",
  "hellhole/Goddy.lev",
  "hellhole/Whale.lev",
  "hellhole/ChangBOP.lev",
  "hellhole/D11base.lev",
  "hellhole/Sancti.lev",
  "hellhole/boxwar.lev",
  "hellhole/Street.lev",
  "hellhole/Mission.lev",
  "hellhole/WWI.lev",
  "hellhole/Circulate.lev",
  "hellhole/eif.lev",
  "hellhole/VILLE.LEV",
  "hellhole/hornillo.lev",
  "hellhole/Land-Ho.lev",
  "hellhole/Ledge.lev",
  "hellhole/VÄLGJORD.lev",
  "hellhole/reactor.lev",
  "hellhole/Drunk.lev",
  "hellhole/KNAPPPPP.LEV",
  "hellhole/TF.LEV",
  "hellhole/Underground.lev",
  "hellhole/BOAT.LEV",
  "hellhole/Mountain_2.lev",
  "hellhole/Ninja rope.lev",
  "hellhole/ST-1.lev",
  "hellhole/Shelves.lev",
  "hellhole/the cave.lev",
  "hellhole/Marichan 127.lev",
  "hellhole/2Forts.lev",
  "hellhole/esko.lev",
  "hellhole/Qrampage.lev",
  "hellhole/Shadowfax.lev",
  "hellhole/TOWERS_1.LEV",
  "hellhole/Paris burning.lev",
  "hellhole/Desert.lev",
  "hellhole/CS HardCore.lev",
  "hellhole/Dirt Pool.lev",
  "hellhole/Port.lev",
  "hellhole/S.O.B.lev",
  "hellhole/Marichan 126.lev",
  "hellhole/TOXIC.LEV",
  "hellhole/venus.lev",
  "hellhole/X2.lev",
  "hellhole/Dog.lev",
  "hellhole/Artic.lev",
  "hellhole/SMB.lev",
  "hellhole/BATTLE F.LEV",
  "hellhole/drknark.lev",
  "hellhole/NCC-1701.lev",
  "hellhole/Fortress_2.lev",
  "hellhole/king.lev",
  "hellhole/VULKAAN.LEV",
  "hellhole/EGHEGHEG.LEV",
  "hellhole/Warfare.lev",
  "hellhole/AntStack.lev",
  "hellhole/Temple2.lev",
  "hellhole/war.lev",
  "hellhole/mushroom.lev",
  "hellhole/desrtsun.lev",
  "hellhole/downtown.lev",
  "hellhole/cells.lev",
  "hellhole/ROCKY CR.LEV",
  "hellhole/Nirvana.lev",
  "hellhole/place.lev",
  "hellhole/funnel.lev",
  "hellhole/neighbours.lev",
  "hellhole/adelanto.lev",
  "hellhole/Court.lev",
  "hellhole/Chan.lev",
  "hellhole/psycho.lev",
  "hellhole/Bot.lev",
  "hellhole/StarBurst.lev",
  "hellhole/Arena 4.lev",
  "hellhole/BGrock.lev",
  "hellhole/blastpit.lev",
  "hellhole/Surface.lev",
  "hellhole/podzemi.lev",
  "hellhole/Interlierobattles.lev",
  "hellhole/KOKKKKO.LEV",
  "hellhole/City Assualt.lev",
  "hellhole/Train.lev",
  "hellhole/glowwalz.lev",
  "hellhole/Temple.lev",
  "hellhole/igo eh muito fei.lev",
  "hellhole/Tribbles.lev",
  "hellhole/SHELTER.LEV",
  "hellhole/boom2.lev",
  "hellhole/Gato400deep.lev",
  "hellhole/Agave.lev",
  "hellhole/bj4wilq.lev",
  "hellhole/Jump.lev",
  "hellhole/Mountain_1.lev",
  "hellhole/Ghousthouse.lev",
  "hellhole/Hungry Dinosaurs.lev",
  "hellhole/Hotel.lev",
  "hellhole/Stupids.lev",
  "hellhole/Super Widget.lev",
  "hellhole/Simple2.lev",
  "hellhole/simples.lev",
  "hellhole/Cross Walls.lev",
  "hellhole/hubba.lev",
  "hellhole/feting fett.lev",
  "hellhole/towers_2.lev",
  "hellhole/THE HUNTERS.lev",
  "hellhole/Giza.lev",
  "hellhole/scud.lev",
  "hellhole/park8.lev",
  "hellhole/Turtle.lev",
  "hellhole/oneside.lev",
  "hellhole/CHAOSI~T.LEV",
  "hellhole/Seven Dragonballs.lev",
  "hellhole/BIGHOUSE.LEV",
  "hellhole/BigCity.lev",
  "hellhole/Mofoc2.lev",
  "hellhole/thorn.lev",
  "hellhole/Galactic Death!.lev",
  "hellhole/Vault city.LEV",
  "hellhole/Kewk.lev",
  "hellhole/RGB.LEV",
  "hellhole/gears.lev",
  "hellhole/FORTRESS_1.LEV",
  "hellhole/Arena 5.lev",
  "hellhole/Nfuel.lev",
  "hellhole/Romulan-Bop.lev",
  "hellhole/alloutwar.lev",
  "hellhole/code.lev",
  "hellhole/UFO_1.LEV",
  "hellhole/dump2.lev",
  "hellhole/pretzel.lev",
  "hellhole/coolbob.lev",
  "hellhole/warfield.lev",
  "hellhole/CTF - Red October.lev",
  "hellhole/cavecastles.lev",
  "hellhole/Lines.lev",
  "hellhole/house2.lev",
  "hellhole/houses.lev",
  "hellhole/COOL_1.LEV",
  "hellhole/bloodycircus.lev",
  "hellhole/crossroad.lev",
  "hellhole/missil2.lev",
  "hellhole/tunnel_1.lev",
  "hellhole/labyrint.lev",
  "hellhole/Fly3.lev",
  "hellhole/Likwid.lev",
  "hellhole/mount ki.lev",
  "hellhole/meander.lev",
  "hellhole/Arena 1.lev",
  "hellhole/Hitler.lev",
  "hellhole/duelroom1.lev",
  "hellhole/raid.lev",
  "hellhole/Fallout.lev",
  "hellhole/Super Mario Bros 3.lev",
  "hellhole/jungle1.lev",
  "hellhole/DIRTHOLE.LEV",
  "hellhole/Curves.lev",
  "hellhole/dump.lev",
  "hellhole/snowdev.lev",
  "hellhole/INDIA2.LEV",
  "hellhole/getebo.lev",
  "hellhole/Crap pile.lev",
  "hellhole/Gollum.lev",
  "hellhole/Tomb.lev",
  "hellhole/medieval.lev",
  "hellhole/MYKKO.LEV",
  "hellhole/Smiley.lev",
  "hellhole/MONGOOSE.LEV",
  "hellhole/MAZEOFDTH.lev",
  "hellhole/Space.lev",
  "hellhole/Roomz.lev",
  "hellhole/THEDRILL.LEV",
  "hellhole/FUN_1.LEV",
  "hellhole/brokan.lev",
  "hellhole/rainyday.lev",
  "hellhole/trench_2.lev",
  "hellhole/LSTBeached.lev",
  "hellhole/toxic_1.lev",
  "hellhole/Domes.lev",
  "hellhole/JoeMac.lev",
  "hellhole/Marichan 134.lev",
  "hellhole/castle.lev",
  "hellhole/aftermath.lev",
  "hellhole/JANNU133.LEV",
  "hellhole/VILLE133.LEV",
  "hellhole/BALL.lev",
  "hellhole/overgrowth.lev",
  "hellhole/MyLevel1.lev",
  "hellhole/Eboat.lev",
  "hellhole/kenny.lev",
  "hellhole/kross31.lev",
  "hellhole/Transit.lev",
  "hellhole/Trenches.lev",
  "hellhole/Elias4.lev",
  "hellhole/Shaft2.lev",
  "hellhole/wormhole_1.lev",
  "hellhole/Mines.lev",
  "hellhole/hangon.lev",
  "hellhole/SNight.lev",
  "hellhole/Lots'O'Bunkers.lev",
  "hellhole/Metal.lev",
  "hellhole/DvDmanDT.lev",
  "hellhole/Missile.lev",
  "hellhole/cathode2.lev",
  "hellhole/Dropzone.lev",
  "hellhole/Type VII.lev",
  "hellhole/mortar duel.lev",
  "hellhole/time.lev",
  "hellhole/rockar.lev",
  "hellhole/crazy.lev",
  "hellhole/arena711.lev",
  "hellhole/viajano.lev",
  "hellhole/COOL_2.LEV",
  "hellhole/cafe.lev",
  "hellhole/cyber.lev",
  "hellhole/tunnel_2.lev",
  "hellhole/warzone.lev",
  "hellhole/Fire.lev",
  "hellhole/Dark City.lev",
  "hellhole/Arena 2.lev",
  "hellhole/pikachu.lev",
  "hellhole/Follow the White Rabbit.lev",
  "hellhole/jungle2.lev",
  "hellhole/Phantosams castle.lev",
  "hellhole/Ak22.lev",
  "hellhole/DIRTFACT.LEV",
  "hellhole/LAB!.lev",
  "hellhole/screen3.lev",
  "hellhole/2xkross.lev",
  "hellhole/Base station.lev",
  "hellhole/boom.lev",
  "hellhole/Worms.lev",
  "hellhole/deathruw.lev",
  "hellhole/Corey's1st.lev",
  "hellhole/MyLevel3.lev",
  "hellhole/sludgestastion.lev",
  "hellhole/Ice Station.lev",
  "hellhole/Surak.lev",
  "hellhole/lamo.lev",
  "hellhole/Saloon.lev",
  "hellhole/Nfactory.lev",
  "hellhole/RED2.LEV",
  "hellhole/dcastle.lev",
  "hellhole/osamabase.lev",
  "hellhole/a21.lev",
  "hellhole/scity.lev",
  "hellhole/METALLIC.LEV",
  "hellhole/OMEGA G.LEV",
  "hellhole/Nuke.lev",
  "hellhole/tetris.lev",
  "hellhole/rebels.lev",
  "hellhole/D-7.lev",
  "hellhole/qaverns.lev",
  "hellhole/X.lev",
  "hellhole/miazga.lev",
  "hellhole/TOURNEY.LEV",
  "hellhole/2BASES.LEV",
  "hellhole/dookie.lev",
  "hellhole/floors.lev",
  "hellhole/TRENCH_1.LEV",
  "hellhole/PERFECT.LEV",
  "hellhole/8xwhell.lev",
  "hellhole/TooMuch.lev",
  "hellhole/datkk.lev",
  "hellhole/Marichan 137.lev",
  "hellhole/MyLevel2.lev",
  "hellhole/Farm.lev",
  "hellhole/COOLER.LEV",
  "hellhole/mega.lev",
  "hellhole/fun.lev",
  "hellhole/NAABRID2.LEV",
  "hellhole/round fort.lev",
  "hellhole/funes.lev",
  "hellhole/nails12.lev",
  "hellhole/The Next D-Day.lev",
  "hellhole/GreyFort.lev",
  "hellhole/alloutwar2.lev",
  "hellhole/leliero.lev",
  "hellhole/The Base.lev",
  "hellhole/britney.lev",
  "hellhole/Arena 3.lev",
  "hellhole/BellFun.lev",
  "hellhole/MarioLnd.lev",
  "hellhole/ANT HILL.LEV",
  "hellhole/wormatras.lev",
  "hellhole/Stripes.lev",
  "hellhole/Area51.lev",
  "hellhole/007.lev",
  "hellhole/Piss.lev",
  "hellhole/Crecent.lev",
  "hellhole/MNGSJL2.LEV",
  "hellhole/cool_3.lev",
  "hellhole/DOMETRY.LEV",
  "hellhole/Mujbojin.lev",
  "hellhole/cathode.lev",
  "hellhole/Dostavnk.lev",
  "hellhole/highway.lev",
  "hellhole/fallout2.lev",
  "hellhole/dropzone_1.lev",
  "hellhole/Dino City 3.lev",
  "hellhole/Flojo.lev",
  "hellhole/FORTFAN.LEV",
  "hellhole/kgivler4.lev",
  "hellhole/Cheesewarz.lev",
  "hellhole/rektum.lev",
  "hellhole/sheep_1.lev",
  "hellhole/MeltDown.lev",
  "hellhole/qmark.lev",
  "hellhole/Rockman & Forte 1.lev",
  "hellhole/viipuri3.lev",
  "hellhole/mining.lev",
  "hellhole/skelett_1.lev",
  "hellhole/NUKESITE.lev",
  "hellhole/Kitchen.lev",
  "hellhole/Cartman_1.lev",
  "hellhole/Training.lev",
  "hellhole/fargerik.lev",
  "hellhole/bloody.lev",
  "hellhole/Wrmfarm.lev",
  "hellhole/office_1.lev",
  "hellhole/CastV2.lev",
  "hellhole/Computer.lev",
  "hellhole/2xkross-s.lev",
  "hellhole/aiTest.lev",
  "hellhole/K_B.LEV",
  "hellhole/base1.lev",
  "hellhole/NX-2000 Excelsior.lev",
  "hellhole/TOM'S.LEV",
  "hellhole/hell_2.lev",
  "hellhole/Stupido.lev",
  "hellhole/Q3arena2.lev",
  "hellhole/kross31-s.lev",
  "hellhole/fara.lev",
  "hellhole/Liero Tournament.lev",
  "hellhole/HOLY CRA.LEV",
  "hellhole/inferno.lev",
  "hellhole/Laardi2.lev",
  "hellhole/Chester Cheetah 1.lev",
  "hellhole/fight.lev",
  "hellhole/kgivler5.lev",
  "hellhole/tunnels_1.lev",
  "hellhole/Hang gown towers.lev",
  "hellhole/bones.lev",
  "hellhole/CLIFF.LEV",
  "hellhole/Bat.lev",
  "hellhole/City_1.lev",
  "hellhole/vulgo.lev",
  "hellhole/hotel_1.lev",
  "hellhole/bomber roof.lev",
  "hellhole/lavina.lev",
  "hellhole/multiplicity2.lev",
  "hellhole/Dino City 2.lev",
  "hellhole/Passage.lev",
  "hellhole/Arena911.lev",
  "hellhole/yums.lev",
  "hellhole/fmfriend.lev",
  "hellhole/skelett.lev",
  "hellhole/ZanderZ.lev",
  "hellhole/Rope.lev",
  "hellhole/ZIMM.LEV",
  "hellhole/DM - Morpheus.lev",
  "hellhole/JIPEE.LEV",
  "hellhole/dojo.lev",
  "hellhole/Water System.lev",
  "hellhole/klex.lev",
  "hellhole/MUSEUM.lev",
  "hellhole/Line.lev",
  "hellhole/Tunnels.LEV",
  "hellhole/tunnel2.lev",
  "hellhole/LodeRun2.lev",
  "hellhole/u96.lev",
  "hellhole/Sk8+Park.lev",
  "hellhole/tiger_1.lev",
  "hellhole/2zamki3.lev",
  "hellhole/Corey's2nd.lev",
  "hellhole/MoonTown.lev",
  "hellhole/shadowr.lev",
  "hellhole/PaakALLO.LEV",
  "hellhole/Myth.lev",
  "hellhole/Supply depot.lev",
  "hellhole/shapeup.lev",
  "hellhole/tdk3.lev",
  "hellhole/heaven.lev",
  "hellhole/Rockman & Forte 2.lev",
  "hellhole/ghostrider_platforms.lev",
  "hellhole/silo attack.lev",
  "hellhole/sfactory.lev",
  "hellhole/Farm_1.lev",
  "hellhole/Nukecore.lev",
  "hellhole/screwed.lev",
  "hellhole/redmonster.lev",
  "hellhole/FBI.lev",
  "hellhole/openjump.lev",
  "hellhole/kyle4.lev",
  "hellhole/lingon.lev",
  "hellhole/CTF-Facing Worlds.lev",
  "hellhole/Pyramid.lev",
  "hellhole/illyria.lev",
  "hellhole/Hell_1.lev",
  "hellhole/sun.lev",
  "hellhole/Q3arena1.lev",
  "hellhole/Rockman & Forte 3.lev",
  "hellhole/X-Mas.lev",
  "hellhole/unite.lev",
  "hellhole/Chester Cheetah 2.lev",
  "hellhole/oilraft.lev",
  "hellhole/TUNNELS_2.lev",
  "hellhole/SNIPER.LEV",
  "hellhole/kgivler6.lev",
  "hellhole/arcorum.lev",
  "hellhole/StarTown.lev",
  "hellhole/CITY_2.LEV",
  "hellhole/Ice cave.lev",
  "hellhole/Ants.lev",
  "hellhole/Memory.lev",
  "hellhole/igor merda.lev",
  "hellhole/Dino City 1.lev",
  "hellhole/Bubbles.lev",
  "hellhole/CommSat1.lev",
  "hellhole/MarcMaze.lev",
  "hellhole/larvalevel.lev",
  "hellhole/DM - Phobos Moon.lev",
  "hellhole/1FORT.LEV",
  "hellhole/Rescue thoos hostage.lev",
  "hellhole/starwars.lev",
  "hellhole/5pipe.lev",
  "hellhole/fools.lev",
  "hellhole/Amasing.lev",
  "hellhole/idiota.lev",
  "hellhole/Trap Map!!!.lev",
  "hellhole/Eclipse.lev",
  "hellhole/station.lev",
  "hellhole/UA-PARK.LEV",
  "hellhole/building_2.lev",
  "hellhole/style.lev",
  "hellhole/snigel.lev",
  "hellhole/kgivler2.lev",
  "hellhole/Mk4 Starliner.lev",
  "hellhole/1701TMP.lev",
  "hellhole/liero500.lev",
  "hellhole/S-Arena.lev",
  "hellhole/vrak.lev",
  "hellhole/AirCastleZ.lev",
  "hellhole/Tightwad.lev",
  "hellhole/Fortress.lev",
  "hellhole/marocko6.lev",
  "hellhole/stripes2.lev",
  "hellhole/Yoshis Island 3.lev",
  "hellhole/VAINU.LEV",
  "hellhole/Volcano_1.lev",
  "hellhole/Fight Eyes_1.lev",
  "hellhole/conduit.lev",
  "hellhole/DYNO.LEV",
  "hellhole/serpent.lev",
  "hellhole/BOMBARD.LEV",
  "hellhole/Bizzare.lev",
  "hellhole/MY MAZE.LEV",
  "hellhole/egypt.lev",
  "hellhole/Fort2.lev",
  "hellhole/Commando_1.lev",
  "hellhole/New Maze.lev",
  "hellhole/arenaaaa.lev",
  "hellhole/Bowsers Cave.lev",
  "hellhole/megarock.lev",
  "hellhole/S.LEV",
  "hellhole/rooms.lev",
  "hellhole/big round fort.lev",
  "hellhole/ZZ-2000.lev",
  "hellhole/Blades Liero Resort.lev",
  "hellhole/TechnoForts.lev",
  "hellhole/OBApipoca.lev",
  "hellhole/lb_vulcn.lev",
  "hellhole/trees.lev",
  "hellhole/Spiral.lev",
  "hellhole/oilraft_1.lev",
  "hellhole/Afterlife.lev",
  "hellhole/stripes3.lev",
  "hellhole/Yoshis Island 2.lev",
  "hellhole/SNIPE.lev",
  "hellhole/death.lev",
  "hellhole/rcoaster.lev",
  "hellhole/two buildings.lev",
  "hellhole/belltoll.lev",
  "hellhole/2worm4ya.lev",
  "hellhole/kgivler3.lev",
  "hellhole/RGY.lev",
  "hellhole/@AT@.LEV",
  "hellhole/Area 51.lev",
  "hellhole/shotgun.lev",
  "hellhole/space_1.lev",
  "hellhole/RV_city.lev",
  "hellhole/building_3.lev",
  "hellhole/misile.lev",
  "hellhole/ToraBora.lev",
  "hellhole/FUCKEMUP.LEV",
  "hellhole/Gato.lev",
  "hellhole/Pes.lev",
  "hellhole/gooya.lev",
  "hellhole/Q3basin.lev",
  "hellhole/StarNite.lev",
  "hellhole/cacoonz.lev",
  "hellhole/pokol2.lev",
  "hellhole/slide.lev",
  "hellhole/$MUMEY$.LEV",
  "hellhole/TODOJUEGOS.lev",
  "hellhole/qmark_1.lev",
  "hellhole/TREECOPY.LEV",
  "hellhole/UA-FORT.LEV",
  "hellhole/Lost Base.lev",
  "hellhole/doublebase.lev",
  "hellhole/Gato400surf.lev",
  "hellhole/orofication.lev",
  "hellhole/Maze2.lev",
  "hellhole/FREE.LEV",
  "hellhole/DK Factory.lev",
  "hellhole/building_1.lev",
  "hellhole/criss_cross.lev",
  "hellhole/kgivler1.lev",
  "hellhole/SMILEEE.LEV",
  "hellhole/red.lev",
  "hellhole/pt109.lev",
  "hellhole/Rain.lev",
  "hellhole/towers.lev",
  "hellhole/Rockman & Forte 4.lev",
  "hellhole/starscape.lev",
  "hellhole/Warehaus.lev",
  "hellhole/Damned.lev",
  "hellhole/volcano_2.lev",
  "hellhole/MY HOUSES.LEV",
  "hellhole/doogsy.lev",
  "hellhole/Fort1.lev",
  "hellhole/kyle3.lev",
  "hellhole/tank.lev",
  "hellhole/Ak.lev",
  "hellhole/Neon.lev",
  "hellhole/cu.lev",
  "hellhole/kyle2.lev",
  "hellhole/moonstreet.lev",
  "hellhole/estatua.lev",
  "hellhole/n3.lev",
  "hellhole/JUSSI999.LEV",
  "hellhole/KNASIGGG.LEV",
  "hellhole/PKiNpow.lev",
  "hellhole/badger.lev",
  "hellhole/Volcano_3.lev",
  "hellhole/Kamn.lev",
  "hellhole/Yoshis Island 1.lev",
  "hellhole/Rockman & Forte 5.lev",
  "hellhole/MM - Pharaoh Man.lev",
  "hellhole/mario.lev",
  "hellhole/Alley.lev",
  "hellhole/fork.lev",
  "hellhole/WG.lev",
  "hellhole/hearcia.lev",
  "hellhole/teraz3.lev",
  "hellhole/OrbitalOffice.lev",
  "hellhole/ArjenRoc.lev",
  "hellhole/wormhole.lev",
  "hellhole/LIAM.LEV",
  "hellhole/Tiger's Warzone.lev",
  "hellhole/panther-s.lev",
  "hellhole/WW2.LEV",
  "hellhole/GPK.lev",
  "hellhole/Roburky1.lev",
  "hellhole/redrock.lev",
  "hellhole/door to door war.lev",
  "hellhole/Ladofdef.lev",
  "hellhole/BOOMERAN.LEV",
  "hellhole/SNAKE.LEV",
  "hellhole/pot.lev",
  "hellhole/FORTISAR.LEV",
  "hellhole/LATMc.lev",
  "hellhole/ICE Rase.lev",
  "hellhole/bomb drop.lev",
  "hellhole/Forest_1.lev",
  "hellhole/uoyt.lev",
  "hellhole/baricade.lev",
  "hellhole/Bone Yard.lev",
  "hellhole/stygg.lev",
  "hellhole/castle_4.lev",
  "hellhole/LABRATH.LEV",
  "hellhole/pokemon_1.lev",
  "hellhole/Garden.lev",
  "hellhole/glowbalz.lev",
  "hellhole/Head_1.lev",
  "hellhole/winning cup.lev",
  "hellhole/TerriostScum.lev",
  "hellhole/Digimon.lev",
  "hellhole/JANNU.LEV",
  "hellhole/REDLAND.LEV",
  "hellhole/DEADLYFL.LEV",
  "hellhole/She.lev",
  "hellhole/Gatoperi.lev",
  "hellhole/words.lev",
  "hellhole/Building.lev",
  "hellhole/HELLRAIN.LEV",
  "hellhole/K7station.lev",
  "hellhole/beach.lev",
  "hellhole/Fin.lev",
  "hellhole/joltjord.lev",
  "hellhole/sokkelo.lev",
  "hellhole/kors.lev",
  "hellhole/lb_infst.lev",
  "hellhole/Volca.lev",
  "hellhole/gard towers.lev",
  "hellhole/Nofly.lev",
  "hellhole/contruction.lev",
  "hellhole/kettle.lev",
  "hellhole/quake2.lev",
  "hellhole/RockCity.lev",
  "hellhole/Block.lev",
  "hellhole/castlez.lev",
  "hellhole/igorbota.lev",
  "hellhole/MM - Air Man.lev",
  "hellhole/quake3.lev",
  "hellhole/vulcano.lev",
  "hellhole/holy.lev",
  "hellhole/liero_war.lev",
  "hellhole/BORDOM.LEV",
  "hellhole/NCC-2100.lev",
  "hellhole/D-day.lev",
  "hellhole/Field_1.lev",
  "hellhole/chick1.lev",
  "hellhole/munchoz.lev",
  "hellhole/areninha.lev",
  "hellhole/RUSH.LEV",
  "hellhole/Lines_1.lev",
  "hellhole/tune-l.lev",
  "hellhole/AirForce.lev",
  "hellhole/BlowAway.lev",
  "hellhole/Pleasegod.lev",
  "hellhole/eyeball.lev",
  "hellhole/Zamek.lev",
  "hellhole/TRYFFEL.LEV",
  "hellhole/1sttrolsaone.lev",
  "hellhole/keep.lev",
  "hellhole/Ultima.lev",
  "hellhole/Blink.lev",
  "hellhole/kego.lev",
  "hellhole/Light.lev",
  "hellhole/SUmutus.lev",
  "hellhole/Tower.lev",
  "hellhole/castle2_1.lev",
  "hellhole/rocket.lev",
  "hellhole/wormstne.lev",
  "hellhole/VERSION.LEV",
  "hellhole/bunkers.lev",
  "hellhole/Warofworms.lev",
  "hellhole/missilem.lev",
  "hellhole/hidnseek.lev",
  "hellhole/funny.lev",
  "hellhole/SKELBASE.LEV",
  "hellhole/Assault.lev",
  "hellhole/gigaworm.lev",
  "hellhole/LodeRun.LEV",
  "hellhole/Chicken Coop.lev",
  "hellhole/Mt.Kewl.lev",
  "hellhole/BirdofPrey.lev",
  "hellhole/PILLBOXES.LEV",
  "hellhole/blink_1.lev",
  "hellhole/Wormhouse.lev",
  "hellhole/alien.lev",
  "hellhole/fiska.lev",
  "hellhole/Office.lev",
  "hellhole/glad.lev",
  "hellhole/Cheese.lev",
  "hellhole/22.lev",
  "hellhole/aaa.lev",
  "hellhole/FURUKEL.LEV",
  "hellhole/Warforts.lev",
  "hellhole/chick2.lev",
  "hellhole/Joes2.lev",
  "hellhole/BGRock2.lev",
  "hellhole/Ptolemy.lev",
  "hellhole/clans.lev",
  "hellhole/tiger-s.lev",
  "hellhole/The arena.lev",
  "hellhole/Ring.lev",
  "hellhole/shroomz.lev",
  "hellhole/HighRock.lev",
  "hellhole/flame.lev",
  "hellhole/cave.lev",
  "hellhole/Simple.lev",
  "hellhole/HiddenCove.lev",
  "hellhole/kaj.lev",
  "hellhole/gubbs.lev",
  "hellhole/ARMORED BUNKER.LEV",
  "hellhole/MIFFFFO.LEV",
  "hellhole/led.lev",
  "hellhole/Hive.lev",
  "hellhole/frontline.lev",
  "hellhole/lvl0005.lev",
  "hellhole/kpack1.lev",
  "hellhole/SPECIAL.LEV",
  "hellhole/VILDSVIN.LEV",
  "hellhole/war_1.lev",
  "hellhole/KUBLA.LEV",
  "hellhole/blob.lev",
  "hellhole/tokara.lev",
  "hellhole/Sone Zeta.lev",
  "hellhole/Statue.lev",
  "hellhole/CTFArena.lev",
  "hellhole/BATTLEDM.LEV",
  "hellhole/cool.lev",
  "hellhole/spike_1.lev",
  "hellhole/woods.lev",
  "hellhole/Enemy Below.lev",
  "hellhole/2Ninjas.lev",
  "hellhole/BATTLEGR.LEV",
  "hellhole/4squares.lev",
  "hellhole/Chip N Dale 2.lev",
  "hellhole/graves.lev",
  "hellhole/derek2.lev",
  "hellhole/glasscup.lev",
  "hellhole/HUSK.LEV",
  "hellhole/pyramid_1.lev",
  "hellhole/Haunted.lev",
  "hellhole/castle_2.lev",
  "hellhole/arena.lev",
  "hellhole/zimmarea.lev",
  "hellhole/Smiley_1.lev",
  "hellhole/Circling.lev",
  "hellhole/ultrar.lev",
  "hellhole/Clime.lev",
  "hellhole/DY-100.lev",
  "hellhole/Bubsy 1.lev",
  "hellhole/UTs Arena.lev",
  "hellhole/Ultron.lev",
  "hellhole/RED_1.LEV",
  "hellhole/Gatodeep.lev",
  "hellhole/Garden_1.lev",
  "hellhole/Chump.lev",
  "hellhole/navarona.lev",
  "hellhole/Doraemon.lev",
  "hellhole/Mk5 Products.lev",
  "hellhole/winter_1.lev",
  "hellhole/tunnel2_1.lev",
  "hellhole/storage.lev",
  "hellhole/Joe & Mac 2.lev",
  "hellhole/CHAOS II.LEV",
  "hellhole/SPIRAL_1.LEV",
  "hellhole/CTF.lev",
  "hellhole/treehaus.lev",
  "hellhole/Ktinga.lev",
  "hellhole/maskheim.lev",
  "hellhole/Artillary.lev",
  "hellhole/Cavern.lev",
  "hellhole/onlyoneway.lev",
  "hellhole/BEAM2.LEV",
  "hellhole/Vgen.lev",
  "hellhole/slottet.lev",
  "hellhole/caves of doom.lev",
  "hellhole/prison.lev",
  "hellhole/WinWord.lev",
  "hellhole/kilemal.lev",
  "hellhole/Mk2 Dry Bulk.lev",
  "hellhole/Mob.lev",
  "hellhole/mountain.lev",
  "hellhole/Hotel 2.lev",
  "hellhole/aswan.lev",
  "hellhole/Big X.lev",
  "hellhole/spacestation.lev",
  "hellhole/TRICKYCL.LEV",
  "hellhole/atr.lev",
  "hellhole/Rock_1.lev",
  "hellhole/Ninja.lev",
  "hellhole/Sky.lev",
  "hellhole/ramp.lev",
  "hellhole/frog.lev",
  "hellhole/UFO.lev",
  "hellhole/team-death.lev",
  "hellhole/dthruw2.lev",
  "hellhole/amplify.lev",
  "hellhole/color.lev",
  "hellhole/UrLord.lev",
  "hellhole/WORMWARS.LEV",
  "hellhole/Head.lev",
  "hellhole/oh no.lev",
  "hellhole/labyrint2.lev",
  "hellhole/Haloween.lev",
  "hellhole/castle_3.lev",
  "hellhole/2xkross2.lev",
  "hellhole/Zeppelin.lev",
  "hellhole/Fletcher DD.lev",
  "hellhole/Chip N Dale 3.lev",
  "hellhole/arkham.lev",
  "hellhole/galleon.lev",
  "hellhole/Cave_1.lev",
  "hellhole/JUSSI133.LEV",
  "hellhole/Cross.lev",
  "hellhole/hill.lev",
  "hellhole/Chip N Dale 1.lev",
  "hellhole/RealTime.lev",
  "hellhole/derek1.lev",
  "hellhole/mineplus.lev",
  "hellhole/Pyramid_2.lev",
  "hellhole/BIN LADE.LEV",
  "hellhole/CASTLE_1.LEV",
  "hellhole/WILD.LEV",
  "hellhole/Bubsy 2.lev",
  "hellhole/shrine.lev",
  "hellhole/Labrinth.lev",
  "hellhole/mystic.lev",
  "hellhole/rubble.lev",
  "hellhole/VermisPit.lev",
  "hellhole/Joe & Mac 1.lev",
  "hellhole/Jee.lev",
  "hellhole/albatros.lev",
  "hellhole/CLONESWR.LEV",
  "hellhole/Nuketest.lev",
  "hellhole/TR2000.lev",
  "hellhole/Xvz.lev",
  "hellhole/stalin.lev",
  "hellhole/DIAMOND.LEV",
  "hellhole/COMMAND.LEV",
  "hellhole/Fight Eyes.lev",
  "hellhole/likwid_1.lev",
  "hellhole/pokol.lev",
  "hellhole/stripes_1.lev",
  "hellhole/Bunkier2.lev",
  "hellhole/fiskboll.lev",
  "hellhole/Bridge of Quai.lev",
  "hellhole/towerwar.lev",
  "hellhole/stronghold.lev",
  "hellhole/arina_1.lev",
  "hellhole/MIJANDO.lev",
  "hellhole/pipeline.lev",
  "hellhole/ohshit.lev",
  "hellhole/ANTS1.LEV",
  "hellhole/Hq.lev",
  "hellhole/BLUE 2.LEV",
  "hellhole/DEATH BO.LEV",
  "hellhole/RADIAL.LEV",
  "hellhole/Mk1 Liquids.lev",
  "hellhole/TheMine.lev",
  "hellhole/diagonal.lev",
  "hellhole/weekyear.lev",
  "hellhole/bloodprk.lev",
  "hellhole/lvl0003.lev",
  "hellhole/bj4.lev",
  "hellhole/MAZE.LEV",
  "hellhole/Tube.lev",
  "hellhole/goku.lev",
  "hellhole/coolbob1.lev",
  "hellhole/dethruw3.lev",
  "hellhole/CRASH.LEV",
  "hellhole/Goku Worm.lev",
  "hellhole/ladofdef_1.lev",
  "hellhole/DM-1.lev",
  "hellhole/casino final.lev",
  "hellhole/SNAKE_1.LEV"
]
